version: '3.8'

services:
  order-service:
    build:
      context: ./order-service
    ports:
      - "5000:5000"
    depends_on:
      - payment-service

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "5001:5001"
